version: "3"

volumes:
  my-db:
networks:
  laravel:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8099:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - laravel

  node:
    image: node:8.16.1
    entrypoint:
      - /bin/bash
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    tty: true
    env_file:
      - .env
    environment:
      - HOME=/var/www/html
    networks:
      - laravel
