version: "3"

volumes:
  my-db:

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8099:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-db:/var/lib/mysql
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./:/var/www/html"
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: root
      FTP_USER_PASS: root
      FTP_USER_HOME: /var
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"
    restart: always
